const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
// Lightweight .env loader: keeps server secrets out of source code/frontend.
(function loadDotEnv(){const f=path.join(__dirname,'.env');if(!fs.existsSync(f))return;for(const raw of fs.readFileSync(f,'utf8').split(/\r?\n/)){const line=raw.trim();if(!line||line.startsWith('#'))continue;const i=line.indexOf('=');if(i<1)continue;const k=line.slice(0,i).trim(),v=line.slice(i+1).trim().replace(/^['\"]|['\"]$/g,'');if(!process.env[k])process.env[k]=v;}})();
const PORT=process.env.PORT||3000, ROOT=__dirname, DBFILE=path.join(ROOT,'data','db.json');
const POSTBACK_SECRET=process.env.TASKO_POSTBACK_SECRET||(process.env.NODE_ENV==='production'?null:'TASKO_SANDBOX_SECRET');
const rateBuckets=new Map();
function rateLimit(key,max,windowMs){const t=Date.now();let x=rateBuckets.get(key);if(!x||t-x.start>=windowMs)x={start:t,count:0};x.count++;rateBuckets.set(key,x);return x.count<=max}
function clientKey(req){return (req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').toString().split(',')[0].trim()}
const now=()=>new Date().toISOString(); const id=p=>p+'_'+crypto.randomBytes(7).toString('hex');
const hash=p=>crypto.scryptSync(p,crypto.randomBytes(16),64).toString('hex');
const verify=(p,h)=>{try{if(!h)return false;if(h.startsWith('scrypt$'))return crypto.timingSafeEqual(Buffer.from(hashWithSalt(p,h),'hex'),Buffer.from(h.split('$')[2],'hex'));return h===p}catch{return false}};
function hashWithSalt(p,h){const a=h.split('$');return crypto.scryptSync(p,Buffer.from(a[1],'hex'),64).toString('hex')}
function mkhash(p){const s=crypto.randomBytes(16).toString('hex');return 'scrypt$'+s+'$'+crypto.scryptSync(p,Buffer.from(s,'hex'),64).toString('hex')}
function load(){
  if(!fs.existsSync(path.dirname(DBFILE))) fs.mkdirSync(path.dirname(DBFILE),{recursive:true});
  if(!fs.existsSync(DBFILE)) fs.writeFileSync(DBFILE,JSON.stringify(seed(),null,2));
  const d=JSON.parse(fs.readFileSync(DBFILE,'utf8'));
  const arrs=['users','admins','advertisers','tasks','attempts','activities','withdrawals','transactions','rewards','redemptions','referrals','tickets','notifications','audits','violations','campaigns','partners','offers','subscriptions','coupons','postbacks','sessions','resetTokens','healthChecks','healthIssues','securityEvents','advertiserRequests','challengeCompletions','oauthStates'];
  for(const k of arrs) if(!Array.isArray(d[k])) d[k]=[];
  d.settings={...seed().settings,...(d.settings||{})};
  d.settings.packages={...seed().settings.packages,...(d.settings?.packages||{})}; for(const k of Object.keys(seed().settings.packages)) d.settings.packages[k]={...seed().settings.packages[k],...(d.settings.packages[k]||{})};
  d.rules={...seed().rules,...(d.rules||{})};
  if(Array.isArray(d.settings.levels)&&d.settings.levels.length){const valid=d.settings.levels.filter(x=>x&&x.id&&Number.isFinite(Number(x.minXP))).sort((a,b)=>Number(a.minXP)-Number(b.minXP)).map((x,i)=>({...x,rank:i+1,minXP:Number(x.minXP)}));if(valid.length)levels=valid;}else{d.settings.levels=levels;}
  d.settings.packagePriorities=d.settings.packagePriorities||{Free:1,Plus:2,Premium:3};
  const prMap={normal:1,low:1,medium:2,high:4,highest:5}; for(const [k,pkg] of Object.entries(d.settings.packages||{})){const n=Number(pkg.priorityRank||pkg.priority);pkg.priorityRank=Number.isFinite(n)&&n>0?Math.min(5,n):(prMap[String(pkg.priority||'').toLowerCase()]||Number(d.settings.packagePriorities[k]||1));pkg.priority=pkg.priorityRank;pkg.status=pkg.status|| (pkg.active?'active':'inactive');}
  d.settings.timezone='Asia/Amman';
  d.settings.healthCheckIntervalMinutes=5;
  d.settings.requirePhoneVerificationForWithdrawal=false;
  d.settings.requireEmailVerificationForWithdrawal=false;
  // Keep the prototype open for testing unless the Owner intentionally closes it.
  if(typeof d.settings.registrationsOpen!=='boolean') d.settings.registrationsOpen=true;
  d.admins=d.users.filter(u=>u.role==='admin').map(u=>({id:u.id,userId:u.id,name:u.name,email:u.email,permissions:u.permissions||[]}));
  for(const c of d.campaigns){if(!c.packageConfigs){const base={points:Number(c.rewardPerPerson||10),xp:Number(c.xp||10),cashReward:0,levelMinId:c.levelMinId||'bronze',maxPerUser:Number(c.maxPerUser||1)};c.packageConfigs={Free:{...base,eligible:(c.packageMin||'Free')==='Free'},Plus:{...base,eligible:(c.packageMin||'Free')==='Plus'},Premium:{...base,eligible:(c.packageMin||'Free')==='Premium'}};}if(c.status==='active'&&!Object.values(c.packageConfigs).some(x=>x.eligible)){c.packageConfigs.Free.eligible=true;c.packageConfigs.Free.points=Number(c.rewardPerPerson||10);c.packageConfigs.Free.xp=Number(c.xp||10);}}
  return d;
}
function save(){fs.mkdirSync(path.dirname(DBFILE),{recursive:true});const tmp=DBFILE+'.'+process.pid+'.'+crypto.randomBytes(4).toString('hex')+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2),{encoding:'utf8',mode:0o600});fs.renameSync(tmp,DBFILE)}
const PERMS=['users','tasks','campaigns','partners','withdrawals','rewards','referrals','subscriptions','fraud','support','reports','audit','settings','sandbox','admins','advertisers','preview'];
let levels=[{id:'bronze',name:'Bronze',minXP:0,rank:1},{id:'silver',name:'Silver',minXP:1500,rank:2},{id:'gold',name:'Gold',minXP:6000,rank:3},{id:'platinum',name:'Platinum',minXP:15000,rank:4},{id:'diamond',name:'Diamond',minXP:30000,rank:5}];
function level(x){if(x&&typeof x==='object'&&x.levelId){const z=levels.find(l=>l.id===x.levelId);if(z)return {id:z.id,name:z.name,min:z.minXP,rank:z.rank,next:levels.find(n=>n.rank===z.rank+1)?.minXP??null}}const v=Number(typeof x==='object'?x.xp:x||0);let l=levels[0];for(const a of levels)if(v>=a.minXP)l=a;return {id:l.id,name:l.name,min:l.minXP,rank:l.rank,next:levels.find(n=>n.rank===l.rank+1)?.minXP??null}}
function levelById(idv){return levels.find(l=>l.id===String(idv))||levels[0]}
function syncLevel(u){const lv=level(Number(u?.xp)||0);u.levelId=lv.id;return lv}
function setLevel(u,idv){const lv=levelById(idv);u.levelId=lv.id;u.xp=lv.minXP;return lv}
function levelRank(u){return level(u).rank}
function minRank(t){return t.levelMinId?levelById(t.levelMinId).rank:(levels.find(l=>l.minXP===Number(t.levelMin||0))?.rank||1)}
function seed(){const owner={id:'owner',name:'Tasko Owner',email:'owner@tasko.test',phone:'+962790000000',password:mkhash('123456'),role:'owner',permissions:PERMS,accountState:'Normal',xp:0,points:0,cash:0,package:'Free',createdAt:now(),lastLogin:null};return {users:[owner],admins:[],advertisers:[],tasks:[{id:'task_demo_video',title:'مشاهدة فيديو',type:'video',points:50,xp:20,duration:120,package:'Free',levelMin:0,verification:'auto',active:true,dailyLimit:5},{id:'task_demo_survey',title:'استبيان قصير',type:'survey',points:150,xp:50,duration:300,package:'Free',levelMin:0,verification:'pending',active:true,dailyLimit:3},{id:'task_demo_test',title:'اختبار موقع',type:'testing',points:300,xp:100,duration:600,package:'Plus',levelMin:1000,verification:'manual',active:true,dailyLimit:2}],attempts:[],activities:[],withdrawals:[],transactions:[],rewards:[],redemptions:[],referrals:[],tickets:[],notifications:[],audits:[],violations:[],campaigns:[],partners:[{id:'par_demo',name:'Donut House',category:'Food',status:'active',vip:false}],offers:[{id:'off_demo',partnerId:'par_demo',title:'دونات مجانية',description:'دونات واحدة عند الاستبدال',pointsCost:1000,levelMin:1000,packageMin:'Free',active:true,usesPerUser:1}],subscriptions:[{id:'Free',name:'Free',price:0,features:['الوصول الأساسي','حدود يومية قياسية']},{id:'Plus',name:'Plus',price:4.99,features:['مهام أكثر','أولوية أفضل','مهام Plus']},{id:'Premium',name:'Premium',price:9.99,features:['أعلى أولوية','ميزات Premium','حدود أعلى']}],settings:{minWithdrawal:5,referralReward:100,referredGift:50,referralQualificationTasks:3,warningLimit:3,tempSuspendLimit:5,banLimit:8,taskDailyLimit:30,pointsPerCash:100,maintenance:false,registrationsOpen:true,tasksOpen:true,withdrawalsOpen:true,emergencyMode:false,emergencyReason:'',packages:{Free:{name:'Free',price:0,currency:'JOD',durationDays:0,active:true,visible:true,dailyTasks:30,weeklyTasks:0,monthlyTasks:0,maxPerTask:1,priority:'normal',minLevel:0,withdrawalMin:5,withdrawalDailyLimit:1,features:['الوصول الأساسي','حدود يومية قياسية']},Plus:{name:'Plus',price:4.99,currency:'JOD',durationDays:30,active:true,visible:true,dailyTasks:60,weeklyTasks:0,monthlyTasks:0,maxPerTask:2,priority:'high',minLevel:0,withdrawalMin:5,withdrawalDailyLimit:3,features:['مهام أكثر','أولوية أفضل','مهام Plus']},Premium:{name:'Premium',price:9.99,currency:'JOD',durationDays:30,active:true,visible:true,dailyTasks:100,weeklyTasks:0,monthlyTasks:0,maxPerTask:3,priority:'highest',minLevel:0,withdrawalMin:5,withdrawalDailyLimit:5,features:['أعلى أولوية','ميزات Premium','حدود أعلى']}}},rules:{passwordMin:8,requireUpper:true,requireLower:true,requireNumber:true,requireSpecial:true},coupons:[],postbacks:[],sessions:[],resetTokens:[]}}
let db=load();
function seededPin(name, fallback){return process.env[name]||null}
function ensureAccount({id:uid,name,email,phone,role,password,company,vip=false,permissions=[],emergencyPin}){
  let u=db.users.find(x=>x.id===uid || x.email===email);
  if(!u){u={id:uid,name,email,phone,password:mkhash(password),role,permissions,accountState:'Normal',xp:0,points:0,cash:0,package:'Free',createdAt:now(),lastLogin:null};if(company)u.company=company;if(emergencyPin)u.emergencyPinHash=mkhash(emergencyPin);db.users.push(u)}
  else {u.password=mkhash(password);u.role=role;u.permissions=role==='owner'?PERMS:(permissions||[]);u.accountState=u.accountState||'Normal';u.phone=u.phone||phone;u.packageStartedAt=u.packageStartedAt||u.createdAt||now();if(emergencyPin)u.emergencyPinHash=mkhash(emergencyPin);}
  if(role==='owner'){u.permissions=PERMS;if(u.id==='owner'){u.name='Tasko Owner';u.phone='+962790000000';}else if(u.id==='owner2'){u.name='Tasko Owner 2';u.phone='+962790000010';}}
  if(role==='advertiser'){
    let ad=db.advertisers.find(x=>x.userId===u.id);
    if(!ad){ad={id:id('advertiser'),userId:u.id,company:company||u.company||name,contact:name,email,status:'active',vip:!!vip,verifiedAt:now()};db.advertisers.push(ad)}
  }
  return u;
}
ensureAccount({id:'owner',name:'Tasko Owner',email:'owner@tasko.test',phone:'+962790000000',role:'owner',password:'123456',emergencyPin:seededPin('TASKO_PIN_OWNER1',null)});
ensureAccount({id:'owner2',name:'Tasko Owner 2',email:'owner2@tasko.test',phone:'+962790000010',role:'owner',password:'Tasko@Owner2',emergencyPin:seededPin('TASKO_PIN_OWNER2',null)});
ensureAccount({id:'admin_demo',name:'Tasko Operations Admin',emergencyPin:seededPin('TASKO_PIN_ADMIN_OPERATIONS',null),email:'admin@tasko.test',phone:'+962790000001',role:'admin',password:'Tasko@Admin1',permissions:['users','tasks','campaigns','withdrawals','support','reports','audit','advertisers','fraud']});
ensureAccount({id:'user_demo',name:'Tasko Demo User',email:'user@tasko.test',phone:'+962790000002',role:'user',password:'Tasko@User1'});
ensureAccount({id:'admin_users',name:'Tasko Users Admin',emergencyPin:seededPin('TASKO_PIN_ADMIN_USERS',null),email:'admin-users@tasko.test',phone:'+962790000004',role:'admin',password:'Tasko@123',permissions:['users','reports','audit','support']});
ensureAccount({id:'admin_tasks',name:'Tasko Tasks Admin',emergencyPin:seededPin('TASKO_PIN_ADMIN_TASKS',null),email:'admin-tasks@tasko.test',phone:'+962790000005',role:'admin',password:'Tasko@123',permissions:['tasks','campaigns','reports','audit']});
ensureAccount({id:'admin_support',name:'Tasko Support Admin',emergencyPin:seededPin('TASKO_PIN_ADMIN_SUPPORT',null),email:'support@tasko.test',phone:'+962790000006',role:'admin',password:'Tasko@123',permissions:['support','users','reports']});
ensureAccount({id:'user1',name:'Tasko Test User 1',email:'user1@tasko.test',phone:'+962790000007',role:'user',password:'Tasko@123'});
ensureAccount({id:'advertiser1',name:'Tasko Advertiser 1',email:'advertiser1@tasko.test',phone:'+962790000008',role:'advertiser',password:'Tasko@123',company:'Tasko Advertiser 1',vip:false});
ensureAccount({id:'vip_advertiser',name:'Tasko VIP Advertiser',email:'vip-advertiser@tasko.test',phone:'+962790000009',role:'advertiser',password:'Tasko@123',company:'Tasko VIP Client',vip:true});
ensureAccount({id:'advertiser_demo',name:'Tasko Demo Advertiser',email:'advertiser@tasko.test',phone:'+962790000003',role:'advertiser',password:'Tasko@Advert1',company:'Demo Advertiser',vip:false});
if(!db.partners.some(x=>x.id==='par_demo')) db.partners.push({id:'par_demo',name:'Donut House',category:'Food',status:'active',vip:false});
if(!db.offers.some(x=>x.id==='off_demo')) db.offers.push({id:'off_demo',partnerId:'par_demo',title:'دونات مجانية',description:'دونات واحدة عند الاستبدال',pointsCost:1000,levelMin:1000,packageMin:'Free',active:true,usesPerUser:1});
if(!db.offers.some(x=>x.id==='off_demo_voucher')) db.offers.push({id:'off_demo_voucher',partnerId:'par_demo',title:'قسيمة تجريبية',description:'خصم تجريبي لاختبار متجر المكافآت',pointsCost:500,levelMin:0,packageMin:'Free',active:true,usesPerUser:1});
if(!db.campaigns.some(x=>x.id==='cmp_demo')) db.campaigns.push({id:'cmp_demo',referenceId:'CMP-DEMO-001',advertiserId:db.advertisers.find(x=>x.userId==='advertiser_demo')?.id||null,name:'حملة تجريبية',objective:'conversion',budget:500,platformRevenue:50,status:'active',trackingId:'clk_demo_001',createdAt:now(),results:{clicks:120,conversions:12,spent:180}});
save();
function json(res,obj,status=200){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, max-age=0','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://challenges.cloudflare.com; frame-src 'self' https://challenges.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://challenges.cloudflare.com; frame-ancestors 'none'"});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>2e6)reject(Error('too large'))});req.on('end',()=>{if(!b)return resolve({});try{resolve(JSON.parse(b))}catch{reject(Error('invalid JSON'))}})})}
function token(){return crypto.randomBytes(32).toString('hex')}
function user(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const s=db.sessions.find(x=>x.token===h.slice(7)&&new Date(x.expires)>new Date());return s?db.users.find(u=>u.id===s.userId):null}
function requireAuth(req,res,roles){const u=user(req);if(!u)return json(res,{error:'Unauthorized'},401);if(roles&&roles.length&&!roles.includes(u.role))return json(res,{error:'Forbidden'},403);return u}
function requirePerm(req,res,p){const u=requireAuth(req,res,['admin','owner']);if(!u)return null;if(u.role!=='owner'&&!u.permissions.includes(p))return json(res,{error:'Permission denied'},403),null;return u}
function requireConfirm(a,b){const supplied=String(b?.confirm||'');if(!/^\d{4}$/.test(supplied))return 'رمز التأكيد المكوّن من 4 أرقام مطلوب';if(!a?.emergencyPinHash)return 'رمز التأكيد الخاص بهذا الحساب غير مضبوط على الخادم';if(!verify(supplied,a.emergencyPinHash))return 'رمز التأكيد الخاص بهذا الحساب غير صحيح';return null}
function audit(u,action,target,meta={}){db.audits.unshift({id:id('audit'),actorId:u?.id||'system',action,target,meta,at:now()});db.audits=db.audits.slice(0,5000)}
function notify(uid,title,message,type='info'){db.notifications.unshift({id:id('ntf'),userId:uid,title,message,type,read:false,at:now()})}
function pwOK(p,email=''){const r=db.rules;if(typeof p!=='string'||p.length<r.passwordMin)return 'كلمة المرور يجب أن تكون 8 أحرف على الأقل';if(r.requireUpper&&!/[A-Z]/.test(p))return 'أضف حرفاً كبيراً';if(r.requireLower&&!/[a-z]/.test(p))return 'أضف حرفاً صغيراً';if(r.requireNumber&&!/\d/.test(p))return 'أضف رقماً';if(r.requireSpecial&&!/[^A-Za-z0-9]/.test(p))return 'أضف رمزاً خاصاً';if(email&&p.toLowerCase().includes(email.split('@')[0].toLowerCase()))return 'كلمة المرور ضعيفة';return null}
function isAdmin(u){return u&&['owner','admin'].includes(u.role)}
function clean(u){if(!u)return null;syncLevel(u);const x={...u};delete x.password;const ps=db.settings.packages?.[u.package||'Free']||{};const started=u.packageStartedAt||u.createdAt||null;const exp=u.packageExpiresAt||null;const days=exp?Math.max(0,Math.ceil((new Date(exp).getTime()-Date.now())/86400000)):null;return {...x,level:level(x),packageInfo:{type:u.package||'Free',subscriptionDate:started,expirationDate:exp,daysRemaining:days,status:exp&&new Date(exp).getTime()<Date.now()?'Expired':'Active',priority:Number(ps.priorityRank||ps.priority||1)}}}
function jordanOffsetMinutes(){return 180}
function parseJordanDate(v){if(!v)return null;const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})(?::(\d{2}))?/);if(!m)return new Date(v).getTime();return Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+(m[6]||0))-jordanOffsetMinutes()*60000}
function jordanNow(){return new Date(Date.now()+jordanOffsetMinutes()*60000).toISOString().slice(0,19).replace('Z','')}
function packageConfigFor(c,pkg){return c.packageConfigs?.[pkg]||null}
function campaignEligibility(u,c){if(c.status!=='active')return 'الحملة غير منشورة';const n=Date.now(),st=parseJordanDate(c.startAtJordan||c.startAt),en=parseJordanDate(c.endAtJordan||c.endAt);if(st&&n<st)return 'الحملة لم تبدأ بعد';if(en&&n>en)return 'انتهت مدة الحملة';const cfg=packageConfigFor(c,u.package||'Free');if(!cfg||cfg.eligible!==true)return 'الباقة الحالية لا تسمح بهذه الحملة';if(cfg.startsAtJordan&&n<parseJordanDate(cfg.startsAtJordan))return 'المهمة غير متاحة لهذه الباقة بعد';if(cfg.endsAtJordan&&n>parseJordanDate(cfg.endsAtJordan))return 'انتهت إتاحة المهمة لهذه الباقة';if(cfg.levelMinId&&levelRank(u)<levelById(cfg.levelMinId).rank)return 'مستوى الحساب غير كافٍ';if(Array.isArray(c.allowedCountries)&&c.allowedCountries.length&&!c.allowedCountries.includes(u.country))return 'الحملة غير متاحة في دولتك';if(c.targeting?.cities?.length&&!c.targeting.cities.includes(u.city))return 'الحملة غير متاحة في مدينتك';if(c.targeting?.genders?.length&&!c.targeting.genders.includes(u.gender))return 'الحملة غير متاحة حسب الاستهداف';if(c.targeting?.minAge||c.targeting?.maxAge){const age=Math.floor((Date.now()-new Date(u.dateOfBirth).getTime())/31557600000);if(!Number.isFinite(age)||(c.targeting.minAge&&age<c.targeting.minAge)||(c.targeting.maxAge&&age>c.targeting.maxAge))return 'الحملة غير متاحة حسب العمر'}return null}
function eligible(u,t){if(!t.active)return 'المهمة غير متاحة';const n=Date.now(),st=parseJordanDate(t.startsAtJordan||t.startsAt),en=parseJordanDate(t.endsAtJordan||t.endsAt);if(st&&n<st)return t.showBeforeStart?'مهمة إضافية قادمة':'المهمة لم تبدأ بعد';if(en&&n>en)return 'انتهت مدة المهمة';if(t.levelMinId&&levelRank(u)<levelById(t.levelMinId).rank)return 'مستوى الحساب غير كافٍ';if(!t.levelMinId&&levelRank(u)<minRank(t))return 'مستوى الحساب غير كافٍ';const order={Free:0,Plus:1,Premium:2};if(order[u.package||'Free']<order[t.packageMin||t.package||'Free'])return 'الباقة الحالية لا تسمح بهذه المهمة';return null}
function adminListUsers(){return db.users.filter(u=>u.role==='user')}
function qualifyReferralIfReady(u){const r=db.referrals.find(x=>x.referredId===u.id&&x.status==='pending');if(!r)return false;const progress=db.attempts.filter(x=>x.userId===u.id&&x.status==='approved').length,required=Math.max(1,Number(db.settings.referralQualificationTasks||3));if(progress<required)return false;r.status='qualified';r.qualifiedAt=now();const ref=db.users.find(x=>x.id===r.referrerId&&x.role==='user'&&x.id!==u.id);if(ref){ref.points+=Number(db.settings.referralReward)||0;db.transactions.push({id:id('tx'),userId:ref.id,type:'referral_reward',points:Number(db.settings.referralReward)|